

name: Create Branch From Issue

on:
  issues:
    types:
      - opened
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN}}
        with:
          branch: '${{ github.event.issue.title }}'
          sha: '${{ github.event.pull_request.head.sha }}'

      - name: Run a multi-line script
        run: echo "Branch created"

