# This is a basic workflow to help you get started with Actions

name: Create Branch From Issue

# Controls when the workflow will run
on:
  issues:
    types:
      - opened
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN}}
        with:
          branch: '${{ github.event.issue.title }}'
          sha: '${{ github.event.pull_request.head.sha }}'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: echo "Branch created"

