name: Create Branch From All Issues
on:
  issues:
    types: [opened]
jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create Branch
          uses: peterjgrainger/action-create-branch@v2.0.1
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            branch: "${{ github.event.issue.title }}"
